package com.sust.bean;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TLog {
	TUser user;
	
    public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}
	

	


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.user_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.operate
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String operate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.date
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date date;
    
    public TLog() {
	}

	public TLog( Integer userId, String operate, Date date) {
		super();
		this.userId = userId;
		this.operate = operate;
		this.date = date;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.id
     *
     * @return the value of t_log.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.id
     *
     * @param id the value for t_log.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.user_id
     *
     * @return the value of t_log.user_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.user_id
     *
     * @param userId the value for t_log.user_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.operate
     *
     * @return the value of t_log.operate
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.operate
     *
     * @param operate the value for t_log.operate
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setOperate(String operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.date
     *
     * @return the value of t_log.date
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.date
     *
     * @param date the value for t_log.date
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
    
}