package com.sust.bean;

public class BuildMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_material.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_material.build_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer buildId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_material.material_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer materialId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_material.id
     *
     * @return the value of build_material.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_material.id
     *
     * @param id the value for build_material.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_material.build_id
     *
     * @return the value of build_material.build_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_material.build_id
     *
     * @param buildId the value for build_material.build_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_material.material_id
     *
     * @return the value of build_material.material_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_material.material_id
     *
     * @param materialId the value for build_material.material_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
}