package com.sust.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.sust.bean.TMaintenance;
import com.sust.bean.TMaintenanceExample;

public interface TMaintenanceMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	long countByExample(TMaintenanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int deleteByExample(TMaintenanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int insert(TMaintenance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int insertSelective(TMaintenance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	List<TMaintenance> selectByExample(TMaintenanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	TMaintenance selectByPrimaryKey(Integer id);
	TMaintenance selectLast();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int updateByExampleSelective(@Param("record") TMaintenance record, @Param("example") TMaintenanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int updateByExample(@Param("record") TMaintenance record, @Param("example") TMaintenanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int updateByPrimaryKeySelective(TMaintenance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_maintenance
	 * @mbg.generated  Wed Dec 11 11:25:01 CST 2019
	 */
	int updateByPrimaryKey(TMaintenance record);
}