package com.sust.dao;

import com.sust.bean.BuildMaintenance;
import com.sust.bean.BuildMaintenanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildMaintenanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    long countByExample(BuildMaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int deleteByExample(BuildMaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int insert(BuildMaintenance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int insertSelective(BuildMaintenance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    List<BuildMaintenance> selectByExample(BuildMaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BuildMaintenance record, @Param("example") BuildMaintenanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_maintenance
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExample(@Param("record") BuildMaintenance record, @Param("example") BuildMaintenanceExample example);
}