package com.sust.dao;

import com.sust.bean.TLog;
import com.sust.bean.TLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    long countByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int deleteByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int insert(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int insertSelective(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    List<TLog> selectByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") TLog record, @Param("example") TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExample(@Param("record") TLog record, @Param("example") TLogExample example);
}