package com.sust.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.bean.BuildMake;
import com.sust.bean.BuildMakeExample;
import com.sust.bean.TBuild;

public interface BuildMakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    long countByExample(BuildMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    int deleteByExample(BuildMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    int deleteByPrimaryKey(BuildMake key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    int insert(BuildMake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    int insertSelective(BuildMake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    List<BuildMake> selectByExample(BuildMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") BuildMake record, @Param("example") BuildMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_make
     *
     * @mbg.generated Mon Feb 03 10:26:17 CST 2020
     */
    int updateByExample(@Param("record") BuildMake record, @Param("example") BuildMakeExample example);
    List<TBuild> selectByBuildId(Integer id);
    List<BuildMake> selectByBuildIdWithMake(Integer id);

	List<BuildMake> selectByMakeIdWithBuild(Integer id);
	int deleteBuildMakeByMakeId(Integer id);
    
}