package com.sust.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.bean.BuildTechnique;
import com.sust.bean.BuildTechniqueExample;
import com.sust.bean.TBuild;
import com.sust.bean.TTechnique;

public interface BuildTechniqueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    long countByExample(BuildTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    int deleteByExample(BuildTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    int deleteByPrimaryKey(BuildTechnique key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    int insert(BuildTechnique record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    int insertSelective(BuildTechnique record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    List<BuildTechnique> selectByExample(BuildTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") BuildTechnique record, @Param("example") BuildTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    int updateByExample(@Param("record") BuildTechnique record, @Param("example") BuildTechniqueExample example);
    List<TBuild> selectTechniqueByBuildId(int id);
    List<BuildTechnique> selectBuildTechniqueByTechniqueId(int id);
    List<BuildTechnique> selectBuildTechniqueByBuildId(int id);
    List<TTechnique> selectTechniqueWithBuildId(int id);
    int deleteBuildTechniqueByTId(int id);
    
    
}