package com.sust.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.bean.BuildImage;
import com.sust.bean.BuildImageExample;

public interface BuildImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	long countByExample(BuildImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	int deleteByExample(BuildImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	int deleteByPrimaryKey(BuildImage key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	int insert(BuildImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	int insertSelective(BuildImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	List<BuildImage> selectByExample(BuildImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	int updateByExampleSelective(@Param("record") BuildImage record, @Param("example") BuildImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	int updateByExample(@Param("record") BuildImage record, @Param("example") BuildImageExample example);
	 List<BuildImage> selectImageByBuildId(Integer id);
}