package com.sust.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.bean.MakeImage;
import com.sust.bean.MakeImageExample;

public interface MakeImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    long countByExample(MakeImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int deleteByExample(MakeImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int insert(MakeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int insertSelective(MakeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    List<MakeImage> selectByExample(MakeImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    MakeImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") MakeImage record, @Param("example") MakeImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByExample(@Param("record") MakeImage record, @Param("example") MakeImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByPrimaryKeySelective(MakeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByPrimaryKey(MakeImage record);
}