package com.sust.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.bean.MaterialImage;
import com.sust.bean.MaterialImageExample;

public interface MaterialImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    long countByExample(MaterialImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int deleteByExample(MaterialImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int insert(MaterialImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int insertSelective(MaterialImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    List<MaterialImage> selectByExample(MaterialImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    MaterialImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") MaterialImage record, @Param("example") MaterialImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByExample(@Param("record") MaterialImage record, @Param("example") MaterialImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByPrimaryKeySelective(MaterialImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    int updateByPrimaryKey(MaterialImage record);
}