package com.sust.dao;

import com.sust.bean.TBulletin;
import com.sust.bean.TBulletinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBulletinMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    long countByExample(TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int deleteByExample(TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    int deleteTBulletinById(Integer id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int insert(TBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int insertSelective(TBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    List<TBulletin> selectByExampleWithBLOBs(TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    List<TBulletin> selectByExample(TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    TBulletin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") TBulletin record, @Param("example") TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TBulletin record, @Param("example") TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int updateByExample(@Param("record") TBulletin record, @Param("example") TBulletinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int updateByPrimaryKeySelective(TBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TBulletin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bulletin
     *
     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
     */
    int updateByPrimaryKey(TBulletin record);

}