package com.sust.dao;

import com.sust.bean.TCollection;
import com.sust.bean.TCollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    long countByExample(TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int deleteByExample(TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int insert(TCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int insertSelective(TCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    List<TCollection> selectByExample(TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    TCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") TCollection record, @Param("example") TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int updateByExample(@Param("record") TCollection record, @Param("example") TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int updateByPrimaryKeySelective(TCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Feb 02 15:29:32 CST 2020
     */
    int updateByPrimaryKey(TCollection record);
}