package com.sust.dao;

import com.sust.bean.TechniqueImage;
import com.sust.bean.TechniqueImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TechniqueImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    long countByExample(TechniqueImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int deleteByExample(TechniqueImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int insert(TechniqueImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int insertSelective(TechniqueImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    List<TechniqueImage> selectByExample(TechniqueImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    TechniqueImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TechniqueImage record, @Param("example") TechniqueImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int updateByExample(@Param("record") TechniqueImage record, @Param("example") TechniqueImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int updateByPrimaryKeySelective(TechniqueImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technique_image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    int updateByPrimaryKey(TechniqueImage record);
}