package com.sust.dao;

import com.sust.bean.TMaterial;
import com.sust.bean.TMaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    long countByExample(TMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int deleteByExample(TMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int insert(TMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int insertSelective(TMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    List<TMaterial> selectByExampleWithBLOBs(TMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    List<TMaterial> selectByExample(TMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMaterial record, @Param("example") TMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TMaterial record, @Param("example") TMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    int updateByExample(@Param("record") TMaterial record, @Param("example") TMaterialExample example);
}