package com.sust.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.bean.TMake;
import com.sust.bean.TTechnique;
import com.sust.bean.TTechniqueExample;

public interface TTechniqueMapper {
	TTechnique selectLast();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    long countByExample(TTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int deleteByExample(TTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int insert(TTechnique record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int insertSelective(TTechnique record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    List<TTechnique> selectByExample(TTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    TTechnique selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") TTechnique record, @Param("example") TTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int updateByExample(@Param("record") TTechnique record, @Param("example") TTechniqueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int updateByPrimaryKeySelective(TTechnique record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_technique
     *
     * @mbg.generated Fri Dec 13 10:58:14 CST 2019
     */
    int updateByPrimaryKey(TTechnique record);
}