package com.sust.bean;

public class TechniqueImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technique_image.id
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technique_image.image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technique_image.technique_id
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    private Integer techniqueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technique_image.id
     *
     * @return the value of technique_image.id
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technique_image.id
     *
     * @param id the value for technique_image.id
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technique_image.image
     *
     * @return the value of technique_image.image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technique_image.image
     *
     * @param image the value for technique_image.image
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technique_image.technique_id
     *
     * @return the value of technique_image.technique_id
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    public Integer getTechniqueId() {
        return techniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technique_image.technique_id
     *
     * @param techniqueId the value for technique_image.technique_id
     *
     * @mbg.generated Mon Dec 23 17:01:53 CST 2019
     */
    public void setTechniqueId(Integer techniqueId) {
        this.techniqueId = techniqueId;
    }

	public TechniqueImage(Integer id, String image, Integer techniqueId) {
		super();
		this.id = id;
		this.image = image;
		this.techniqueId = techniqueId;
	}

	public TechniqueImage() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}