package com.sust.bean;

public class TMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_material.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_material.name
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_material.pic
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_material.content
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_material.id
     *
     * @return the value of t_material.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_material.id
     *
     * @param id the value for t_material.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_material.name
     *
     * @return the value of t_material.name
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_material.name
     *
     * @param name the value for t_material.name
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_material.pic
     *
     * @return the value of t_material.pic
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_material.pic
     *
     * @param pic the value for t_material.pic
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_material.content
     *
     * @return the value of t_material.content
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_material.content
     *
     * @param content the value for t_material.content
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}