package com.sust.bean;

public class TMake {
	private TBuild tBuild;
	
    public TBuild gettBuild() {
		return tBuild;
	}

	public void settBuild(TBuild tBuild) {
		this.tBuild = tBuild;
	}
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_make.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_make.name
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_make.type
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_make.pic
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_make.content
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_make.id
     *
     * @return the value of t_make.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_make.id
     *
     * @param id the value for t_make.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_make.name
     *
     * @return the value of t_make.name
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_make.name
     *
     * @param name the value for t_make.name
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_make.type
     *
     * @return the value of t_make.type
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_make.type
     *
     * @param type the value for t_make.type
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_make.pic
     *
     * @return the value of t_make.pic
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_make.pic
     *
     * @param pic the value for t_make.pic
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_make.content
     *
     * @return the value of t_make.content
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_make.content
     *
     * @param content the value for t_make.content
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

	@Override
	public String toString() {
		return "TMake [tBuild=" + tBuild + ", id=" + id + ", name=" + name + ", type=" + type + ", pic=" + pic
				+ ", content=" + content + "]";
	}
    
}