package com.sust.bean;

public class BuildMaintenance {
	private TBuild build;
	private TMaintenance maintenance;
	
	public TBuild getBuild() {
		return build;
	}

	public void setBuild(TBuild build) {
		this.build = build;
	}

	public TMaintenance getMaintenance() {
		return maintenance;
	}

	public void setMaintenance(TMaintenance maintenance) {
		this.maintenance = maintenance;
	}
	
	@Override
	public String toString() {
		return "BuildMaintenance [build=" + build + ", maintenance=" + maintenance + ", id=" + id + ", buildId="
				+ buildId + ", maintenanceId=" + maintenanceId + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_maintenance.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_maintenance.build_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer buildId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_maintenance.maintenance_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    private Integer maintenanceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_maintenance.id
     *
     * @return the value of build_maintenance.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_maintenance.id
     *
     * @param id the value for build_maintenance.id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_maintenance.build_id
     *
     * @return the value of build_maintenance.build_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_maintenance.build_id
     *
     * @param buildId the value for build_maintenance.build_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_maintenance.maintenance_id
     *
     * @return the value of build_maintenance.maintenance_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public Integer getMaintenanceId() {
        return maintenanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_maintenance.maintenance_id
     *
     * @param maintenanceId the value for build_maintenance.maintenance_id
     *
     * @mbg.generated Mon Nov 11 22:31:06 CST 2019
     */
    public void setMaintenanceId(Integer maintenanceId) {
        this.maintenanceId = maintenanceId;
    }
}