package com.sust.bean;

import java.io.Serializable;

public class BuildImage implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column build_image.build_id
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	private Integer buildId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column build_image.image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column build_image.build_id
	 * @return  the value of build_image.build_id
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	public Integer getBuildId() {
		return buildId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column build_image.build_id
	 * @param buildId  the value for build_image.build_id
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	public void setBuildId(Integer buildId) {
		this.buildId = buildId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column build_image.image
	 * @return  the value of build_image.image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column build_image.image
	 * @param image  the value for build_image.image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table build_image
	 * @mbg.generated  Mon Feb 03 11:16:28 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", buildId=").append(buildId);
		sb.append(", image=").append(image);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
	
	
	public BuildImage( String image, Integer buildId) {
		super();
		this.image = image;
		this.buildId = buildId;
	}
	
	public BuildImage() {};
}