package com.sust.bean;

import java.io.Serializable;

public class BuildTechnique implements Serializable {
	private TBuild build;
	private TTechnique techniques;
	
    public TBuild getBuild() {
		return build;
	}

	public void setBuild(TBuild build) {
		this.build = build;
	}

	public TTechnique getTechniques() {
		return techniques;
	}

	public void setTechniques(TTechnique techniques) {
		this.techniques = techniques;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_technique.build_id
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    private Integer buildId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_technique.technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    private Integer technique;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_technique.build_id
     *
     * @return the value of build_technique.build_id
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_technique.build_id
     *
     * @param buildId the value for build_technique.build_id
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_technique.technique
     *
     * @return the value of build_technique.technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    public Integer getTechnique() {
        return technique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_technique.technique
     *
     * @param technique the value for build_technique.technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
    public void setTechnique(Integer technique) {
        this.technique = technique;
    }

	@Override
	public String toString() {
		return "BuildTechnique [build=" + build + ", techniques=" + techniques + ", buildId=" + buildId + ", technique="
				+ technique + "]";
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_technique
     *
     * @mbg.generated Tue Feb 04 11:04:53 CST 2020
     */
  
}