package com.sust.bean;

public class MaterialImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_image.id
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_image.image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_image.material_id
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    private Integer materialId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_image.id
     *
     * @return the value of material_image.id
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_image.id
     *
     * @param id the value for material_image.id
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_image.image
     *
     * @return the value of material_image.image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_image.image
     *
     * @param image the value for material_image.image
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_image.material_id
     *
     * @return the value of material_image.material_id
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_image.material_id
     *
     * @param materialId the value for material_image.material_id
     *
     * @mbg.generated Sat Dec 21 22:22:26 CST 2019
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
}