package com.sust.bean;

import java.io.Serializable;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TBulletin implements Serializable{
	private SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
	private TUser user;
	
	
	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}
	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.id
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private Integer id;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.title
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private String title;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.date
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private Date date;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.user_id
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private Integer userId;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.views
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private Integer views;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.pic
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private String pic;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_bulletin.content
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private String content;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database table t_bulletin
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    private static final long serialVersionUID = 1L;

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.id
	     *
	     * @return the value of t_bulletin.id
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public Integer getId() {
	        return id;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.id
	     *
	     * @param id the value for t_bulletin.id
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setId(Integer id) {
	        this.id = id;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.title
	     *
	     * @return the value of t_bulletin.title
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public String getTitle() {
	        return title;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.title
	     *
	     * @param title the value for t_bulletin.title
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setTitle(String title) {
	        this.title = title;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.date
	     *
	     * @return the value of t_bulletin.date
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public Date getDate() {
	        return date;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.date
	     *
	     * @param date the value for t_bulletin.date
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setDate(Date date) {
	        this.date = date;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.user_id
	     *
	     * @return the value of t_bulletin.user_id
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public Integer getUserId() {
	        return userId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.user_id
	     *
	     * @param userId the value for t_bulletin.user_id
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setUserId(Integer userId) {
	        this.userId = userId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.views
	     *
	     * @return the value of t_bulletin.views
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public Integer getViews() {
	        return views;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.views
	     *
	     * @param views the value for t_bulletin.views
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setViews(Integer views) {
	        this.views = views;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.pic
	     *
	     * @return the value of t_bulletin.pic
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public String getPic() {
	        return pic;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.pic
	     *
	     * @param pic the value for t_bulletin.pic
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setPic(String pic) {
	        this.pic = pic;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column t_bulletin.content
	     *
	     * @return the value of t_bulletin.content
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public String getContent() {
	        return content;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column t_bulletin.content
	     *
	     * @param content the value for t_bulletin.content
	     *
	     * @mbg.generated Tue Jan 21 22:53:32 CST 2020
	     */
	    public void setContent(String content) {
	        this.content = content;
	    }

		@Override
		public String toString() {
			return "TBulletin [format=" + format + ", user=" + user + ", id=" + id + ", title=" + title + ", userId="
					+ userId + ", views=" + views + ", pic=" + pic + ", content=" + content + "]";
		}

	   
	
}