package com.sust.bean;

public class TImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.id
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.image
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.build_id
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    private Integer buildId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.id
     *
     * @return the value of t_image.id
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.id
     *
     * @param id the value for t_image.id
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.image
     *
     * @return the value of t_image.image
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.image
     *
     * @param image the value for t_image.image
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.build_id
     *
     * @return the value of t_image.build_id
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.build_id
     *
     * @param buildId the value for t_image.build_id
     *
     * @mbg.generated Thu Dec 19 22:33:53 CST 2019
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }
}